export const projects = [
  {
    id: 1,
    title: "Spain",
    img: "./assest/spain.png",
    desc: "Travel guide to Spain ",
    link: "https://spain-presentation.osieltorres.repl.co/",
  },
  {
    id: 2,
    title: "Ecommerce",
    img: "./assest/eccomerce.png",
    link: "https://exotic-snacks.herokuapp.com/",
    github: "https://github.com/OsielTorresg/ReactE",
    desc: " Japanese snacks website",
  },
  {
    id: 3,
    title: "Netflix",
    img: "./assest/netflix.png",
    link: "https://netflix-redesign-project.herokuapp.com/",
    github: "https://github.com/Dood3l/netflix-redesign",
    desc: "Redesign Website",
  },
  {
    id: 4,
    title: "Quick Health",
    img: "./assest/quickhealth.png",
    link: "https://edwine97.github.io/hopehacks-g3/index.html",
    github: "https://github.com/EdwinE97/hopehacks-g3",
    desc: "Find your local clinic",
  },
  {
    id: 5,
    title: "Tic-Tac-Toe",
    img: "./assest/tic-tac-to.png",
    desc: "Game",
    link: "https://r2hgame.netlify.app/",
    github: "https://github.com/OsielTorresg/tic-tac-toe-hooks",
  },
];
